# pvc-63378926-bf51-4c91-bc5a-8672450ef37b
apiVersion: v1
kind: PersistentVolume
metadata:
  name: restore-alertmanager-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: azuredisk-ssd-lrs
  azureDisk:
    diskName: ""
    diskURI: ""
    kind: Managed
    cachingMode: None